### ISSUE TITLE
ERROR:root:Error while getting cookie from wozwaardeloket.nl: 405 Client Error

### ISSUE THREAD

**Issue by tuxcrafter** [wpeterw/wozpy#6]
```
ERROR:root:Error while getting cookie from wozwaardeloket.nl: 405 Client Error: Method Not Allowed for url: https://www.wozwaardeloket.nl/wozwaardeloket-api/v1/session/start
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/wozpy/woz.py", line 22, in __get_cookie
    response.raise_for_status()
  File "/usr/local/lib/python3.11/dist-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 405 Client Error: Method Not Allowed for url: https://www.wozwaardeloket.nl/wozwaardeloket-api/v1/session/start
ERROR:root:An error occurred while fetching WOZ data: 'NoneType' object has no attribute 'get'
```

**Comment by tuxcrafter** [comment]
requests.post > requests.get
response = requests.get(url=url, timeout=timeout)
woz_base_url naar: >
woz_base_url: str = "https://api.kadaster.nl/lvwoz/wozwaardeloket-api/v1/wozwaarde/nummeraanduiding/"

verder ben ik met nog wat wijzigingen aan de status code aan het kijken.

**Comment by tuxcrafter** [comment]
```
        for nummeraanduiding_id in nummeraanduiding_ids:
            url = f"{self.settings.woz_base_url}{nummeraanduiding_id}"
            #response = requests.get(url=url, headers=headers, timeout=5).json()
            response = requests.get(url=url, headers=headers, timeout=5)
            if response.status_code == 429:
                print(response.status_code)
                response.json = lambda: {"error": "Too Many Requests"}
            results.append(response.json())
        return results
```
